Whitelist
CodetiviteCore/codetivite-backend pull request #24
Opened 2023-11-01 10:10 UTC by Adaobi-Chuks

2023-11-01 15:20 UTC, king-Alex-d-great requested changes

2023-11-02 07:12 UTC, Adaobi-Chuks commented on lib/handlers/whitelist-handler.js
> +    const whitelistSchema = Joi.object({email: Joi.string().email().required()});
Thank you for your feedback, I now use `value.email` to find by ID and check for temporary email, also used it in creating a new whitelist model.

2023-11-02 07:12 UTC, Adaobi-Chuks commented on lib/handlers/whitelist-handler.js
> +    if (isTemporaryEmail(email)) {
Done

2023-11-02 07:12 UTC, Adaobi-Chuks commented on lib/middlewares/isWhitelisted.js
> +    console.log(request.user)
Let's pretend like this didn't happen😁

2023-11-02 07:27 UTC, Adaobi-Chuks commented on lib/routes/v1/auth-routes.js
> +.post("/magic-login", isWhitelisted, loginWithMagicLink);
So I just went ahead to validate the user in the handler instead, hope this is better.

2023-11-03 09:27 UTC, king-Alex-d-great approved these changes

2023-11-03 09:27 UTC, merged